branch-defaults:
  main:
    environment: Pronoia-env
  build:
    environment: Pronoia-env
environment-defaults:
  Pronoia-env:
    branch: null
    repository: null
global:
  application_name: pronoia
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  # profile: pro
  sc: git
  workspace_type: Application
